# Generated by Django 5.0.3 on 2024-04-01 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='occupation',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
